In [16]:
import os
import pandas as pd
import mysql.connector

# Connect to your Chuka Electronics DB
conn = mysql.connector.connect(
    host='localhost',
    user='root',
    password=os.getenv('DB_PASSWORD'),  # set DB_PASSWORD env var
    database='chuka_electronics'
)

# Pull the data into a Pandas Table (DataFrame)
df = pd.read_sql("SELECT * FROM Customers", conn)
df = pd.read_sql("SELECT * FROM sales", conn)
df = pd.read_sql("SELECT * FROM Products", conn)

# Close and display
conn.close()
df.head(10) # This shows the first 10 rows beautifully!

C:\Users\mawia\AppData\Local\Temp\ipykernel_17052\3586134635.py:14: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql("SELECT * FROM Customers", conn)
C:\Users\mawia\AppData\Local\Temp\ipykernel_17052\3586134635.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql("SELECT * FROM sales", conn)
C:\Users\mawia\AppData\Local\Temp\ipykernel_17052\3586134635.py:16: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql("SELECT * FROM Products", conn)

   product_id          product_name  unit_price  stock_quantity
0           1             HP Laptop     45000.0              10
1           2        iphone charger      1500.0              67
2           3               macbook     45000.0              52
3           4       samsung charger       900.0             104
4           5         amtec speaker      4500.0              25
5           6            lg speaker      7500.0              98
6           7  powerpoint extention       450.0             249
7           8              lg mouse       500.0              86
8           9           led keybord      3600.0              75

In [20]:
# Merge sales and products to see names and prices
# We use 'product_id' as the common link (The Foreign Key)
merged_df = pd.merge(df_sales, df_products, on='product_id')

# Calculate the total for each sale
merged_df['total_price'] = merged_df['stock_quantity'] * merged_df['unit_price']

# Show the results
merged_df.head()

,sale_id,customer_id,product_id,sale_date,product_name,unit_price,stock_quantity,total_price
0,1,1,1,2026-01-29,HP Laptop,45000.0,10,450000.0
1,2,2,4,2026-02-02,samsung charger,900.0,104,93600.0
2,3,5,5,2026-02-02,amtec speaker,4500.0,25,112500.0
3,4,3,7,2026-02-02,powerpoint extention,450.0,249,112050.0
4,5,2,9,2026-02-02,led keybord,3600.0,75,270000.0